<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="gk" failures="1" tests="1" name="Test" time="5.303" errors="0" timestamp="2025-02-14T23:04:17 IST">
  <testcase classname="testCases.EndToEndTestCase" name="verifyE2EFuncionality" time="2.554">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No New Todo Created expected [New Todo created successfully!3] but found [New Todo created successfully!]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
No New Todo Created expected [New Todo created successfully!3] but found [New Todo created successfully!]
at testCases.EndToEndTestCase.verifyE2EFuncionality(EndToEndTestCase.java:132)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verifyE2EFuncionality -->
</testsuite> <!-- Test -->
